# Site settings
title: "thechelsuk"
description: "All the links, socials, and resources"
url: "https://links.thechels.uk"
baseurl: "/"
avatar: "assets/logo.png"

# Social - Row of icons at the top
social:
  - title: "Reddit"
    description: "Check out r/hiydapp & r/tomozapp"
    url: "https://reddit.com/user/thechelsuk"
    icon: "fab fa-reddit"

  - title: "YouTube"
    description: "Watch my videos on YouTube"
    url: "https://youtube.com/thechelsuk"
    icon: "fab fa-youtube"

  - title: "Twitch"
    description: "Watch me live on Twitch"
    url: "https://twitch.tv/thechelsuk"
    icon: "fab fa-twitch"

  - title: "Mastodon"
    description: "Follow & chat on Mastodon"
    url: "https://mastodon.social/@Thechelsuk"
    icon: "fab fa-mastodon"

  - title: "X (Twitter)"
    description: "Follow me for updates"
    url: "https://x.com/thechelsuk"
    icon: "fab fa-x-twitter"

  - title: "Signal"
    description: "Private messaging"
    url: "https://signal.me/#eu/BizXBBg5kvZWt8bjNg-TNpekSp9dJMBUXzLlNCaYil27chQ_yoVItr5fBPF9n0jE"
    icon: "fa-brands fa-signal-messenger"

  - title: "Keybase"
    description: "Verify my identity on Keybase"
    url: "https://keybase.io/thechelsuk"
    icon: "fa-brands fa-keybase"

# links - customize with your own
links:
  - title: "Website"
    description: "Official website."
    url: "https://thechels.uk"
    icon: "fas fa-home"

  - title: "Ko-fi"
    description: "Support me on Ko-fi."
    url: "https://ko-fi.com/thechelsuk"
    icon: "fas fa-coffee"

  - title: "Throne"
    description: "Gift with privacy with Throne."
    url: "https://throne.com/thechelsuk"
    icon: "fa-brands fa-web-awesome"

  - title: "Store"
    description: "Buy apps, fonts, and more on Gumroad."
    url: "https://shop.thechels.uk"
    icon: "fas fa-shopping-cart"

  - title: "App store"
    description: "Check out my iOS apps."
    url: "https://apps.apple.com/gb/developer/mat-benfield/id1818791310"
    icon: "fa-brands fa-app-store"

  - title: "Apple Music"
    description: "Listen to my curated monthly playlists."
    url: "https://music.apple.com/profile/thechelsuk"
    icon: "fab fa-itunes-note"

  - title: "Redbubble"
    description: "Shop for merchandise."
    url: "https://thechelsuk.redbubble.com/"
    icon: "fas fa-tshirt"

  - title: "Shutterstock"
    description: "Photography."
    url: "https://www.shutterstock.com/g/thechelsuk?rid=476625451&utm_source=ctrbreferral-link"
    icon: "fas fa-camera"

  - title: "Hiyd"
    description: "Hiyd App - Official marketing site."
    url: "https://hiyd.uk"
    icon: "fas fa-flask"

  - title: "GitHub"
    description: "Codes and projects."
    url: "https://github.com/thechelsuk"
    icon: "fab fa-github"

  - title: "Drafts Actions"
    description: "Scripts and actions for Drafts."
    url: "https://directory.getdrafts.com/search?utf8=âœ“&q=thechelsuk"
    icon: "fas fa-file-code"

# Footer links
footer_links:
  - title: "home"
    url: "https://thechels.uk"
    type: "website"
    
  - title: "Tomoz"
    url: "https://apps.apple.com/gb/app/tomoz/id6748755747"
    type: "app"

  - title: "ShortKeys"
    url: "https://apps.apple.com/gb/app/shortkeys/id6755919256"
    type: "app"

  - title: "Hiyd"
    url: "https://apps.apple.com/gb/app/hiyd/id6746853559"
    type: "app"
    
  - title: "EngMan"
    url: "https://apps.apple.com/gb/app/engman/id6747295473"
    type: "app"
    
  - title: "Mltply"
    url: "https://apps.apple.com/gb/app/mltply/id6747147316"
    type: "app"

  - title: "tools"
    url: "https://tools.thechels.uk"
    type: "website"

  - title: "feeds"
    url: "https://feeds.thechels.uk"
    type: "website"

  - title: "cod"
    url: "https://cod.thechels.uk"
    type: "website"

  - title: "privacy"
    url: "https://thechels.uk/.well-known/privacy.txt"
    type: "website"

  - title: "security"
    url: "https://thechels.uk/.well-known/security.txt"
    type: "website"

# Build settings
markdown: kramdown
include:
  - assets/webfonts
keep_files:
  - assets/webfonts
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
